#!/bin/bash
getUserDataFunc()
	{
		echo -e "\033[93m\e[4m\n---<USER INFO>---\n\e[24m"
		UIDmin=$(grep "^UID_MIN" /etc/login.defs)
		UIDmax=$(grep "^UID_MAX" /etc/login.defs)
		echo -e "\033[36mSrc:/etc/login.defs\n   ->\033[39m Defined ID Range: \n\033[35m$UIDmin\033[39m | \033[35m$UIDmax\033[39m"
			#Finds low and high UsrID, then print all UID's low += max, excludes root
		echo -e "\n\033[36mSrc:/etc/passwd\n   \033[36m->\033[39m All non-root users:\n\nuserName :x: UID# : [Alias] : /homeDir/ : shell\e[35m"
		awk -F':' -v "min=${UIDmin#UID_MIN}" -v "max=${UIDmax##UID_MAX}" '{ if ( $3 >= min && $3 <= max ) print $0}' /etc/passwd
		#echo -e "\e[0m\033[36m\nDefault Permitted Groups:
		echo -e "\n\e[0m\033[36m   ->\033[0m Default Permitted Groups:\n\ngroupID : x : GID# : [Alias]	\033[35m"
			getent group root
			getent group sudo
	}
getLoginSecurityConfFunc()
 	{
		logGoodLogins=$(grep "^LOG_OK_LOGINS" /etc/login.defs)
		passwordMaxDays=$(grep "^PASS_MAX_DAYS" /etc/login.defs)
		loginRetries=$(grep "^LOGIN_RETRIES" /etc/login.defs)
		loginTimeout=$(grep "^LOGIN_TIMEOUT" /etc/login.defs)
		passwordEncryptionMethod=$(grep "^ENCRYPT_METHOD" /etc/login.defs)
		echo -e "\n\033[36mSrc:/etc/passwd\n   ->\033[39m Current Login Config:\n"
		echo -e "\033[35m$logGoodLogins\n$passwordMaxDays\n$loginRetries\n$loginTimeout\n$passwordEncryptionMethod\e[0m"
	}
getUFWConfFunc()
	{
		#/etc/default/ufw && /etc/ufw/sysctl.conf
		ufwStatus=$(sudo ufw status)
		ufwDefault=$(grep "^DEFAULT" /etc/default/ufw)
		echo -e "$ufwStatus\n$ufwDefault\n"
	}
echo -e "\n\n\n\n\n\n\n\n\n\n ------- ------- ------- ------- ------- ------- ------- ------- ------- ------- ------- ------- -------
\e[1m\e[92m^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^\e[0m\n\033[33m 
	   █████████             █████                                                          
 	 ███░░░░░███           ░░███                                                           
	 ███     ░░░  █████ ████ ░███████   ██████  ████████                                    
	░███         ░░███ ░███  ░███░░███ ███░░███░░███░░███                                   
	░███          ░███ ░███  ░███ ░███░███████  ░███ ░░░                                    
	░░███     ███ ░███ ░███  ░███ ░███░███░░░   ░███                                        
	 ░░█████████  ░░███████  ████████ ░░██████  █████                                       
	  ░░░░░░░░░    ░░░░░███ ░░░░░░░░   ░░░░░░  ░░░░░                                        
	               ███ ░███                                                                 
	              ░░██████                                                                  
	               ░░░░░░                                                                   
	 ███████████             █████               ███            █████       ████   ████████ 
	░░███░░░░░███           ░░███               ░░░            ░░███       ░░███  ███░░░░███
	 ░███    ░███  ██████   ███████   ████████  ████   ██████  ███████      ░███ ░███   ░███
	 ░██████████  ░░░░░███ ░░░███░   ░░███░░███░░███  ███░░███░░░███░       ░███ ░░█████████
	 ░███░░░░░░    ███████   ░███     ░███ ░░░  ░███ ░███ ░███  ░███        ░███  ░░░░░░░███
	 ░███         ███░░███   ░███ ███ ░███      ░███ ░███ ░███  ░███ ███    ░███  ███   ░███
	 █████       ░░████████  ░░█████  █████     █████░░██████   ░░█████     █████░░████████ 
	░░░░░         ░░░░░░░░    ░░░░░  ░░░░░     ░░░░░  ░░░░░░     ░░░░░     ░░░░░  ░░░░░░░░  
\033[39m"
echo -e "\e[1m\e[92m^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^\e[0m
------- ------- ------- ------- ------- ------- ------- ------- ------- ------- ------- ------- -------"
displayUsrOption()
{
echo -e "\n\033[36m	VIEWS:\n\033[93m\n <USER DATABASE> - (1) <LOGIN SECURIT> - (2) <UFW CUR STATS> - (3)"
echo -e "\n\033[36m CONFS:\n\033[93m\n <RE PRIVLEDGER> - (a) <GLOBAL PASSWD> - (b) <UFW EASY CONF> - (d)\033[39m\n"
}
declare -i timeout=0
while [ $timeout -eq 0 ]; do
	displayUsrOption
	input=0;
	read -sn1 input
		if [ $input -eq 1 ]; then
			getUserDataFunc	
			echo -e "\n\033[94m\e[1m0 to return\e[0m"
			while [ $input -ne 0 ]; do 
				read -sn1 input
			done
		elif [ $input -eq 2 ]; then
			getLoginSecurityConfFunc
			echo -e "\n\033[94m\e[1m0 to return\e[0m"
			while [ $input -ne 0 ]; do 
				read -sn1 input
			done
		elif [ $input -eq 3 ]; then
			getUFWConfFunc
			echo -e "\n\033[94m\e[1m0 to return\e[0m"
			while [ $input -ne 0 ]; do 
				read -sn1 input
			done
		else
			echo -e "\n\033[91m\e[1mInvalid input\e[0m"
		fi
	done
